#!/bin/sh
set -e

if [ ! -d /sys/class/net/usb0 ]; then
    exit 0
fi

ip link set usb0 down 2>/dev/null || true
ip addr replace 192.168.7.2/24 dev usb0 2>/dev/null || true
ip link set usb0 up 2>/dev/null || true

exit 0
