#@TYPE: Machine
#@NAME: RaspberryPi0 2 W USB Gadget
#@DESCRIPTION: Raspberry Pi Zero 2 W with USB gadget networking

include conf/machine/raspberrypi0-2w.conf

ENABLE_DWC2_PERIPHERAL = "1"
CMDLINE_DWC_OTG = ""
CMDLINE_RNDIS = "modules-load=dwc2,g_ether"
