#@TYPE: Machine
#@NAME: Raspberry Pi Zero 2 W USB
#@DESCRIPTION: Raspberry Pi Zero 2W with SSH over USB and UART.

include conf/machine/raspberrypi0-2w.conf

ENABLE_DWC2_PERIPHERAL = "1"
ENABLE_UART = "1"
MACHINE_FEATURES:append = " usbgadget"
MACHINE_FEATURES:remove = " bluetooth wifi"
CMDLINE_EXTRA ?= "console=ttyAMA0,115200"
